name: Deploy GitHub Pages And Sync to Gitee

on:
  push:
    branches:
      - main
    paths-ignore: 
      - LICENSE
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout 
        uses: actions/checkout@main

      - name: Set USERNAME and REPO_NAME
        run: |
          echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
          echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV

      - name: Setup Node  
        uses: actions/setup-node@main
        with:
          node-version: "lts/*"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true   

      - name: Build 🔧 
        run: |
          pnpm build

      - name:  Push To GitHub Pages
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          build_dir: dist
          github_token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:${{ env.REPO_NAME }}.git
          destination-repo: git@gitee.com:${{ env.REPO_NAME }}.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{ env.USERNAME }}
          gitee-password: ${{ secrets.GITEE_PSWD }}
          gitee-repo: ${{ env.REPO_NAME }}
          branch: gh-pages
